# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Firebase_Auth' do
    
    #Firebase and RNFirebase pods
    pod 'Firebase/Core'
    
    # Authentication module for RNFirebase
    pod 'Firebase/Auth'
    
    pod 'Firebase/Database'
    

    
    
    
    
end


